"use client";

import type { ExecutionMetadata, Finding } from "@/lib/types";

interface ReviewSummaryProps {
  summary: string;
  findings?: Finding[];
  executionMetadata?: ExecutionMetadata;
}

function formatDuration(ms: number): string {
  if (ms < 1000) {
    return `${ms}ms`;
  }
  const seconds = Math.round(ms / 1000);
  return `${seconds}s`;
}

function formatTokens(tokens: number): string {
  if (tokens >= 1000) {
    return `${(tokens / 1000).toFixed(1)}k`;
  }
  return tokens.toString();
}

function FindingsStats({ findings }: { findings: Finding[] }) {
  const counts = {
    critical: findings.filter((f) => f.severity === "critical").length,
    high: findings.filter((f) => f.severity === "high").length,
    medium: findings.filter((f) => f.severity === "medium").length,
    low: findings.filter((f) => f.severity === "low").length,
  };

  const total = findings.length;

  if (total === 0) {
    return null;
  }

  return (
    <div className="flex flex-wrap items-center gap-4">
      {counts.critical > 0 && (
        <div className="flex items-center gap-2">
          <div className="h-2 w-2 rounded-full bg-red-600 dark:bg-red-500" />
          <span className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
            {counts.critical}
          </span>
          <span className="text-xs text-zinc-600 dark:text-zinc-400">Critical</span>
        </div>
      )}
      {counts.high > 0 && (
        <div className="flex items-center gap-2">
          <div className="h-2 w-2 rounded-full bg-orange-600 dark:bg-orange-500" />
          <span className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
            {counts.high}
          </span>
          <span className="text-xs text-zinc-600 dark:text-zinc-400">High</span>
        </div>
      )}
      {counts.medium > 0 && (
        <div className="flex items-center gap-2">
          <div className="h-2 w-2 rounded-full bg-yellow-500 dark:bg-yellow-400" />
          <span className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
            {counts.medium}
          </span>
          <span className="text-xs text-zinc-600 dark:text-zinc-400">Medium</span>
        </div>
      )}
      {counts.low > 0 && (
        <div className="flex items-center gap-2">
          <div className="h-2 w-2 rounded-full bg-blue-600 dark:bg-blue-500" />
          <span className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
            {counts.low}
          </span>
          <span className="text-xs text-zinc-600 dark:text-zinc-400">Low</span>
        </div>
      )}
    </div>
  );
}

export function ReviewSummary({
  summary,
  findings,
  executionMetadata,
}: ReviewSummaryProps) {
  const hasSummary = summary && summary.trim() !== "";

  return (
    <div className="flex w-full flex-col gap-4">
      {/* Stats Panel */}
      {findings && findings.length > 0 && (
        <div className="rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 shadow-sm">
          <div className="px-4 py-3 border-b border-zinc-200 dark:border-zinc-700">
            <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100 mb-3">
              Overview
            </h3>
            <FindingsStats findings={findings} />
          </div>
          {hasSummary && (
            <div className="px-4 py-3">
              <p className="text-sm leading-relaxed text-zinc-700 dark:text-zinc-300 whitespace-pre-wrap wrap-break-word">
                {summary}
              </p>
            </div>
          )}
          {executionMetadata && (
            <div className="px-4 py-2.5 border-t border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-800/50">
              <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-zinc-600 dark:text-zinc-400">
                <span className="font-medium">
                  Generated by {executionMetadata.agent_count} AI agent
                  {executionMetadata.agent_count !== 1 ? "s" : ""}
                </span>
                <span>·</span>
                <span>{formatDuration(executionMetadata.duration_ms)}</span>
                {executionMetadata.total_tokens > 0 && (
                  <>
                    <span>·</span>
                    <span>{formatTokens(executionMetadata.total_tokens)} tokens</span>
                  </>
                )}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Summary only (if no findings) */}
      {hasSummary && (!findings || findings.length === 0) && (
        <div className="flex w-full flex-col gap-3">
          <h3 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">
            Summary
          </h3>
          <div className="rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 shadow-sm">
            <div className="p-4">
              <p className="text-sm leading-relaxed text-zinc-700 dark:text-zinc-300 whitespace-pre-wrap wrap-break-word">
                {summary}
              </p>
            </div>
            {executionMetadata && (
              <div className="border-t border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-800/50 px-4 py-2.5">
                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-zinc-600 dark:text-zinc-400">
                  <span className="font-medium">
                    Generated by {executionMetadata.agent_count} AI agent
                    {executionMetadata.agent_count !== 1 ? "s" : ""}
                  </span>
                  <span>·</span>
                  <span>{formatDuration(executionMetadata.duration_ms)}</span>
                  {executionMetadata.total_tokens > 0 && (
                    <>
                      <span>·</span>
                      <span>{formatTokens(executionMetadata.total_tokens)} tokens</span>
                    </>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
